POST http://localhost:8080/api/score
Content-Type: application/json

{
  "game": "blockpuzzle",
  "player": "insdgd",
  "points": "1000",
  "playedOn": "2021-04-22T12:40:33"
}

###
GET http://localhost:8080/api/score/blockpuzzle
Accept: application/json
###

POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "blockpuzzle",
  "player": "msdaa",
  "rating": "1",
  "ratedOn": "2021-04-22T12:40:33"
}

###
GET http://localhost:8080/api/rating/avg/blockpuzzle
Accept: application/json

###

POST http://localhost:8080/api/comment
Content-Type: application/json

{
  "game": "blockpuzzle",
  "player": "mansda",
  "comment": "afad af dfsdfaf af a",
  "commentedOn": "2021-04-22T12:40:33"
}

###
GET http://localhost:8080/api/comment/BlockPuzzle
Accept: application/json